# TOUCHPAD SETTINGS TO 
# 	DISABLE WHILE TYPING
# 	ENABLE TAP TO CLICK
# 	MAP TO LEFT RIGHT AND MIDDLE CLICK FOR 1, 2 AND 3 FINGERS RESPECTIVELY
# 	ENABLE NATURAL SCROLLING
input "type:touchpad" {
    dwt enabled
    dwtp enabled
    tap enabled
    tap_button_map lrm
    natural_scroll enabled
}

# KEYBIND TO TOGGLE WAYBAR
bindsym $mod+o exec killall -SIGUSR1 waybar

# KEYBIND TO CHANGE WORKSPACE
#bindsym Alt+l workspace next
#bindsym Alt+h workspace prev

# AUTOHIDE THE WAYBAR: // NOT WORKING TILL NOW.
#bar {
#    swaybar_command waybar
#    position top
#    hidden_state hide
#    mode hide
#    modifier Mod4
#}

# DISABLE BORDERS FOR TILES AND FLOATING WINDOWS
default_border none
default_floating_border none

# SET WALLPAPER
output * bg /home/sol/Pictures/2.png fill

# SET SCALING OF DISPLAY
output eDP-1 scale 1.25

# MAP CAPSLOCK TO ESC AND SHIFT+CAPSLOCK TO TOGGLE CAPSLOCK
input * xkb_options caps:escape_shifted_capslock

# Assign apps to specific workspaces
#assign [app_id="foot"] workspace 1        # or "foot", "kitty", etc.
#assign [app_id="org.mozilla.firefox"] workspace 2
#assign [app_id="Logseq"] workspace 3    # regex match for Logseq AppImage

# Auto-start apps on login
#exec alacritty                                  # launches on workspace 1
#exec firefox                                    # launches on workspace 2
#exec /path/to/Logseq.AppImage                  # launches on workspace 3

for_window [app_id="Logseq"] move scratchpad

# Capture active output to clipboard
bindsym Shift+Print exec grimshot copy output

# Capture active window to clipboard
bindsym Shift+Alt+Print exec grimshot copy active

# Select and capture a custom area to clipboard
bindsym Shift+Ctrl+Print exec grimshot copy area  

# 3-finger swipe right → go to previous workspace
bindgesture swipe:3:right workspace prev

# 3-finger swipe left → go to next workspace
bindgesture swipe:3:left workspace next

# 4-finger tap → Play/Pause
bindgesture hold:4 exec playerctl play-pause

# 4-finger swipe left → Next track
bindgesture swipe:4:left exec playerctl next

# 4-finger swipe right → Previous track
bindgesture swipe:4:right exec playerctl previous

# 3-finger swipe up → Split vertically
#bindgesture swipe:3:up exec swaymsg split v

# 3-finger swipe down → Split horizontally
#bindgesture swipe:3:down exec swaymsg split h

# 3-finger swipe up → Show scratchpad
bindgesture swipe:3:up exec swaymsg scratchpad show

# 3-finger swipe down → move focused window to scratchpad
bindgesture swipe:3:down exec swaymsg move scratchpad


