# TOUCHPAD SETTINGS TO 
# 	DISABLE WHILE TYPING
# 	ENABLE TAP TO CLICK
# 	MAP TO LEFT RIGHT AND MIDDLE CLICK FOR 1, 2 AND 3 FINGERS RESPECTIVELY
# 	ENABLE NATURAL SCROLLING
input "type:touchpad" {
    dwt enabled
    dwtp enabled
    tap enabled
    tap_button_map lrm
    natural_scroll enabled
}

# KEYBIND TO TOGGLE WAYBAR
bindsym $mod+o exec killall -SIGUSR1 waybar

# KEYBIND TO CHANGE WORKSPACE
#bindsym Alt+l workspace next
#bindsym Alt+h workspace prev

# AUTOHIDE THE WAYBAR: // NOT WORKING TILL NOW.
#bar {
#    swaybar_command waybar
#    position top
#    hidden_state hide
#    mode hide
#    modifier Mod4
#}

# DISABLE BORDERS FOR TILES AND FLOATING WINDOWS
default_border none
default_floating_border none

#********************************
#                               *
#       DISPLAY SETTINGS        *
#                               *
#********************************

# SET WALLPAPER
output eDP-1 bg /home/sol/Pictures/5.png fill

# SET SCALING OF DISPLAY
output eDP-1 resolution 1920x1080@60Hz
output eDP-1 scale 1.25
output eDP-1 subpixel rgb
output eDP-1 scale_filter smart
output eDP-1 render_bit_depth 10
output eDP-1 color_profile icc "~/.local/share/icc/display_profile.icc"

# MAP CAPSLOCK TO ESC AND SHIFT+CAPSLOCK TO TOGGLE CAPSLOCK
input * xkb_options caps:escape_shifted_capslock

# ASSIGN APPS TO SPECIFIC WORKSPACES
assign [app_id="foot"]    → workspace 1
assign [app_id="firefox"] → workspace 2
# assign [app_id="Logseq"] → workspace 3
assign [app_id="gnome-terminal"] → workspace 3


# LAUNCH APPS ON STARTUP
exec foot
exec firefox
exec ~/AppImages/Logseq-linux-x64-0.10.15.AppImage
exec gnome-terminal

# LAUNCH APPS IN SCRATCHPAD 
for_window [app_id="Logseq"] move scratchpad
for_window [app_id="spotify"] move scratchpad

#********************************************
#                                           *
#   GESTURE BINDING TO SPECIFIC ACTIONS     *
#                                           *
#********************************************
# 3-finger swipe right → go to previous workspace
bindgesture swipe:3:right workspace prev

# 3-finger swipe left → go to next workspace
bindgesture swipe:3:left workspace next

# 4-finger tap → Play/Pause
bindgesture hold:4 exec playerctl play-pause

# 4-finger swipe left → Next track
bindgesture swipe:4:left exec playerctl next

# 4-finger swipe right → Previous track
bindgesture swipe:4:right exec playerctl previous

# 3-finger swipe up → Split vertically
#bindgesture swipe:3:up exec swaymsg split v

# 3-finger swipe down → Split horizontally
#bindgesture swipe:3:down exec swaymsg split h

# 3-finger swipe up → Show scratchpad
bindgesture swipe:3:up exec swaymsg scratchpad show

# 3-finger swipe down → move focused window to scratchpad
bindgesture swipe:3:down exec swaymsg move scratchpad

# SET 4 FINGER SWIP UP/DOWN FOR INCREASING/DECREASING VOLUME
bindgesture swipe:4:up exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindgesture swipe:4:down exec pactl set-sink-volume @DEFAULT_SINK@ -5%

#  SET 3 FINGER PINCH INWARD TO LAUNCH ROFI
bindgesture pinch:3:inward exec rofi -show drun

# SET 4 FINGER PINCH OUTWARD TO TOGGLE FULLSCREEN
bindgesture pinch:4:outward fullscreen toggle

# ALT + SPACE FOR ROFI
bindsym Alt_L+space exec rofi -show drun -theme Monokai

# Switch between windows on current workspace
bindsym Alt+Tab focus next sibling
bindsym Alt+Shift+Tab focus prev sibling
